#### pytorch fashionmnist数据集 神经网络搭建和训练

In [1]:
# 导入必要包
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision.transforms.v2 import ToTensor     # 转换图像数据为张量
from torchvision.datasets import FashionMNIST
from torch.utils.data import DataLoader  # 数据加载器

In [4]:
# 定义超参数
LR = 1e-3
epochs = 20
BATCH_SIZE = 128

In [2]:
# 数据集加载
train_data = FashionMNIST(root='./fashion_data', train=True, download=True, 
                          transform=ToTensor())
test_data = FashionMNIST(root='./fashion_data', train=False, download=True,
                         transform=ToTensor())


D:\anaconda\envs\py312\Lib\site-packages\torchvision\transforms\v2\_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(


100%|██████████| 26421880/26421880 [00:28<00:00, 926640.63it/s] 


Extracting ./fashion_data\FashionMNIST\raw\train-images-idx3-ubyte.gz to ./fashion_data\FashionMNIST\raw



100%|██████████| 29515/29515 [00:00<00:00, 171877.18it/s]


Extracting ./fashion_data\FashionMNIST\raw\train-labels-idx1-ubyte.gz to ./fashion_data\FashionMNIST\raw



100%|██████████| 4422102/4422102 [00:01<00:00, 2430452.07it/s]


Extracting ./fashion_data\FashionMNIST\raw\t10k-images-idx3-ubyte.gz to ./fashion_data\FashionMNIST\raw



100%|██████████| 5148/5148 [00:00<00:00, 2563185.78it/s]

Extracting ./fashion_data\FashionMNIST\raw\t10k-labels-idx1-ubyte.gz to ./fashion_data\FashionMNIST\raw



In [5]:
trian_dl = DataLoader(train_data, batch_size=BATCH_SIZE, shuffle=True)  # shuffle=True表示打乱数据

In [6]:
# 定义模型
model = nn.Sequential(
    nn.Linear(784, 64),
    nn.Sigmoid(),
    nn.Linear(64, 10)
)

In [7]:
# 损失函数&优化器
loss_fn = nn.CrossEntropyLoss()  # 交叉熵损失函数
# 优化器（模型参数更新）
optimizer = torch.optim.SGD(model.parameters(), lr=LR)

In [8]:
for epoch in range(epochs):
    # 提取训练数据
    for data, target in trian_dl:
        # 前向运算
        output = model(data.reshape(-1, 784))
        # 计算损失
        loss = loss_fn(output, target)
        # 反向传播
        optimizer.zero_grad()  # 所有参数梯度清零
        loss.backward()     # 计算梯度（参数.grad）
        optimizer.step()    # 更新参数

    print(f'Epoch:{epoch} Loss: {loss.item()}')

Epoch:0 Loss: 2.2857069969177246
Epoch:1 Loss: 2.2631423473358154
Epoch:2 Loss: 2.231226921081543
Epoch:3 Loss: 2.211827039718628
Epoch:4 Loss: 2.1842730045318604
Epoch:5 Loss: 2.1698246002197266
Epoch:6 Loss: 2.1168951988220215
Epoch:7 Loss: 2.085740327835083
Epoch:8 Loss: 2.0359115600585938
Epoch:9 Loss: 1.991316795349121
Epoch:10 Loss: 1.9555292129516602
Epoch:11 Loss: 1.9563227891921997
Epoch:12 Loss: 1.9174541234970093
Epoch:13 Loss: 1.857980728149414
Epoch:14 Loss: 1.8308792114257812
Epoch:15 Loss: 1.7410039901733398
Epoch:16 Loss: 1.753538966178894
Epoch:17 Loss: 1.706119179725647
Epoch:18 Loss: 1.6357468366622925
Epoch:19 Loss: 1.6081619262695312


In [9]:
# 测试
test_dl = DataLoader(test_data, batch_size=BATCH_SIZE)

correct = 0
total = 0
with torch.no_grad():  # 不计算梯度
    for data, target in test_dl:
        output = model(data.reshape(-1, 784))
        _, predicted = torch.max(output, 1)  # 返回每行最大值和索引
        total += target.size(0)  # size(0) 等效 shape[0]
        correct += (predicted == target).sum().item()

print(f'Accuracy: {correct/total*100}%')

Accuracy: 63.68000000000001%


In [37]:
output.shape

torch.Size([16, 10])

In [38]:
output

tensor([[ 0.7106,  0.8785, -0.1803,  1.0234,  0.0766, -0.4353,  0.3032, -0.8123,
         -0.3382, -0.9447],
        [ 0.2478,  0.2866,  0.1531,  0.3065,  0.2537, -0.3192,  0.2848, -0.4605,
         -0.2112, -0.5077],
        [-0.9912, -0.9169, -0.5881, -0.8673, -0.8319,  1.2307, -0.5986,  1.6067,
          0.6698,  0.8221],
        [-0.4897, -0.4990, -0.2623, -0.5509, -0.4960,  0.7915, -0.2614,  0.5336,
          0.4207,  0.7446],
        [-0.8052, -0.9985, -0.2462, -0.8899, -0.5261,  0.8487, -0.3545,  1.0531,
          0.8594,  0.7138],
        [ 0.3496,  0.0185,  0.6358,  0.1455,  0.6804, -0.7108,  0.5375, -0.9249,
         -0.1498, -0.6098],
        [-0.1780, -0.5339,  0.0127, -0.4437, -0.2375,  0.4187, -0.0231,  0.0425,
          0.2355,  0.7069],
        [ 0.3762,  0.0183,  0.4654,  0.0826,  0.4296, -0.5662,  0.4794, -0.7506,
         -0.0687, -0.5219],
        [-0.0352, -0.3220,  0.2027, -0.0063,  0.1437, -0.1635,  0.1686, -0.2900,
          0.4962, -0.0548],
        [-0.9556, -

In [31]:
predicted

tensor([3, 3, 7, 5, 7, 4, 9, 6, 8, 9, 1, 9, 1, 3, 1, 7])

In [32]:
target

tensor([3, 2, 7, 5, 8, 4, 5, 6, 8, 9, 1, 9, 1, 8, 1, 5])

In [35]:
(predicted == target).int().sum()

tensor(11)